name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '15' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('./{package.json,pnpm-lock.yaml}') }}
      - name: install dependencies
        run: npm install -g pnpm && pnpm install
      - name: build ts
        run: npm run build
      - name: run tests
        run: npm run test
