name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('./package.json', './pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node${{ matrix.node }}-
      - name: install dependencies
        run: npm install -g pnpm && pnpm install
      - name: build ts
        run: npm run build
      - name: run tests
        run: npm run test
